version: '3'
services:
  llm-rag-app-1:
    container_name: llm-rag-app-1
    build: .
    ports:
      - "8001:8001"
    env_file:
      - .env
    command: poetry run uvicorn src.sample_apps.app_1.src.main:app --host 0.0.0.0 --port 8001