# fly.toml app configuration file generated for llm-sample-app on 2023-12-26T18:49:31-08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "llm-sample-app"
primary_region = "sjc"

[build]

[http_service]
  internal_port = 8001
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024
